# DataCamp: Introduction to Python

**Course:** Introduction to Python  
**Track:** Data Analyst with Python  
**Platform:** DataCamp  
**Started:** January 14, 2026  
**Status:** In Progress  
**Duration:** 4 hours

---

## Course Overview

This course covers Python fundamentals essential for data analysis:

### Topics Covered:
1. **Python Basics** - Variables, data types, operators
2. **Python Lists** - Creating, indexing, slicing, methods
3. **Functions and Packages** - Built-in functions, importing packages
4. **NumPy** - Arrays, array operations, 2D arrays

### Learning Objectives:
- Store and manipulate data using Python variables
- Work with different data types (int, float, str, bool)
- Create and manipulate lists
- Use functions to perform operations
- Leverage NumPy for numerical computing

---

## Chapter 1: Python Basics

### 1.1 The Python Interface

In [1]:
# Basic print statement
print("Hello, World!")
print("Python for Data Analysis")

Hello, World!
Python for Data Analysis


In [2]:
# Python as a calculator
print(5 + 5)
print(10 - 3)
print(4 * 6)
print(20 / 5)

10
7
24
4.0


#### 💡 My Experiments:

In [3]:
# Can I calculate my study hours per month?
hours_per_day = 3.5
days_per_week = 7
weeks_per_month = 4

monthly_hours = hours_per_day * days_per_week * weeks_per_month
print(f"I study {monthly_hours} hours per month!")

# What about hours per year?
yearly_hours = monthly_hours * 12
print(f"That's {yearly_hours} hours per year - almost 1,200 hours!")

I study 98.0 hours per month!
That's 1176.0 hours per year - almost 1,200 hours!


### 1.2 Variables and Types

In [4]:
# Create variables
height = 1.79
weight = 68.7

print(height)
print(weight)

1.79
68.7


In [5]:
# Calculate BMI
bmi = weight / height ** 2
print(f"BMI: {bmi}")

BMI: 21.44127836209856


In [6]:
# Different data types
name = "Manuel"           # String (str)
age = 35                  # Integer (int)
height = 1.79             # Float (float)
is_learning = True        # Boolean (bool)

# Check types
print(type(name))
print(type(age))
print(type(height))
print(type(is_learning))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>


#### 💡 My Experiments:

In [7]:
# What happens when I mix types?
savings = 2000          # int
growth_rate = 0.05      # float

# Python automatically converts to float when needed
future_value = savings * (1 + growth_rate)
print(f"Type of result: {type(future_value)}")
print(f"After one year: ${future_value}")

# Can I convert types explicitly?
savings_str = "5000"
savings_int = int(savings_str)
print(f"Converted string to int: {savings_int}, type: {type(savings_int)}")

Type of result: <class 'float'>
After one year: $2100.0
Converted string to int: 5000, type: <class 'int'>


### 1.3 Type Conversion

In [8]:
# String concatenation vs addition
savings = 100
print("I started with $" + str(savings) + " in my savings account.")

# Or using f-strings (better!)
print(f"I started with ${savings} in my savings account.")

I started with $100 in my savings account.
I started with $100 in my savings account.


In [9]:
# Convert string to float
savings_str = "194.87"
savings_float = float(savings_str)
print(f"Type: {type(savings_float)}, Value: {savings_float}")

Type: <class 'float'>, Value: 194.87


#### 💡 My Experiments:

In [10]:
# Can I convert boolean to int?
is_employed = True
employment_status = int(is_employed)
print(f"True as int: {employment_status}")  # True = 1

is_unemployed = False
print(f"False as int: {int(is_unemployed)}")  # False = 0

# This could be useful for counting!
day1_studied = True
day2_studied = True
day3_studied = False
day4_studied = True

total_days_studied = int(day1_studied) + int(day2_studied) + int(day3_studied) + int(day4_studied)
print(f"I studied {total_days_studied} out of 4 days this week!")

True as int: 1
False as int: 0
I studied 3 out of 4 days this week!


---

## Chapter 2: Python Lists

### 2.1 Creating Lists

In [11]:
# Create a list
fam = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]
print(fam)

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]


In [12]:
# List of lists
fam2 = [["liz", 1.73],
        ["emma", 1.68],
        ["mom", 1.71],
        ["dad", 1.89]]

print(fam2)

[['liz', 1.73], ['emma', 1.68], ['mom', 1.71], ['dad', 1.89]]


#### 💡 My Experiments:

In [13]:
# Create a list of my skills as I learn them
skills = ["Python", "SQL", "Excel", "Git"]
print(f"Current skills: {skills}")

# Can I create a list of mixed types? YES!
learning_journey = [
    "Data Analyst",           # str
    37,                        # int - months in journey
    25.0,                      # float - hours per week
    True,                      # bool - is active
    ["Python", "SQL", "ML"]    # list - skills to learn
]

print(f"\nMy journey: {learning_journey}")
print(f"Type of journey: {type(learning_journey)}")
print(f"Number of elements: {len(learning_journey)}")

Current skills: ['Python', 'SQL', 'Excel', 'Git']

My journey: ['Data Analyst', 37, 25.0, True, ['Python', 'SQL', 'ML']]
Type of journey: <class 'list'>
Number of elements: 5


### 2.2 Subsetting Lists

In [14]:
# Subset and conquer
fam = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]

# Zero-indexed!
print(fam[0])    # First element
print(fam[3])    # Fourth element
print(fam[-1])   # Last element
print(fam[-2])   # Second to last

liz
1.68
1.89
dad


In [15]:
# List slicing
print(fam[3:5])     # Elements at index 3 and 4
print(fam[:4])      # First 4 elements
print(fam[5:])      # From index 5 to end

[1.68, 'mom']
['liz', 1.73, 'emma', 1.68]
[1.71, 'dad', 1.89]


#### 💡 My Experiments:

In [16]:
# Practice with my own data
monthly_savings = [500, 750, 600, 800, 900, 850, 700, 950, 1000, 880, 920, 1100]

# Get Q1 savings (Jan-Mar)
q1_savings = monthly_savings[:3]
print(f"Q1 savings: {q1_savings}")
print(f"Q1 total: ${sum(q1_savings)}")

# Get last 3 months
recent_months = monthly_savings[-3:]
print(f"\nLast 3 months: {recent_months}")
print(f"Recent average: ${sum(recent_months) / len(recent_months):.2f}")

# Every other month (bimonthly)
bimonthly = monthly_savings[::2]
print(f"\nBimonthly review: {bimonthly}")

Q1 savings: [500, 750, 600]
Q1 total: $1850

Last 3 months: [880, 920, 1100]
Recent average: $966.67

Bimonthly review: [500, 600, 900, 700, 1000, 920]


### 2.3 Manipulating Lists

In [17]:
# Replace list elements
fam = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]
fam[0] = "lisa"
print(fam)

['lisa', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]


In [18]:
# Replace slice
fam[0:2] = ["lisa", 1.74]
print(fam)

['lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]


In [19]:
# Add elements to list
fam_ext = fam + ["me", 1.79]
print(fam_ext)

['lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'me', 1.79]


In [20]:
# Delete elements
del fam[2]
print(fam)

['lisa', 1.74, 1.68, 'mom', 1.71, 'dad', 1.89]


#### 💡 My Experiments:

In [21]:
# Building my skills list dynamically
skills = ["Excel", "Bookkeeping"]  # Starting skills
print(f"Starting skills: {skills}")

# Add new skills as I learn them
skills = skills + ["Python"]
print(f"After Week 1: {skills}")

skills = skills + ["SQL", "Git"]
print(f"After Week 2: {skills}")

# Update a skill (more specific)
skills[0] = "Advanced Excel"
print(f"Updated skills: {skills}")

# Remove outdated skill
del skills[1]  # Remove "Bookkeeping" as I transition to tech
print(f"Tech-focused skills: {skills}")

Starting skills: ['Excel', 'Bookkeeping']
After Week 1: ['Excel', 'Bookkeeping', 'Python']
After Week 2: ['Excel', 'Bookkeeping', 'Python', 'SQL', 'Git']
Updated skills: ['Advanced Excel', 'Bookkeeping', 'Python', 'SQL', 'Git']
Tech-focused skills: ['Advanced Excel', 'Python', 'SQL', 'Git']


In [22]:
# IMPORTANT: Understanding list copying behavior
x = ["a", "b", "c"]
y = x           # This creates a reference, not a copy!
y[1] = "z"

print(f"x: {x}")  # x is also changed!
print(f"y: {y}")

# To create a true copy:
x = ["a", "b", "c"]
y = x[:]        # Or use list(x) or x.copy()
y[1] = "z"

print(f"\nx: {x}")  # x is unchanged
print(f"y: {y}")

x: ['a', 'z', 'c']
y: ['a', 'z', 'c']

x: ['a', 'b', 'c']
y: ['a', 'z', 'c']


---

## Chapter 3: Functions and Packages

### 3.1 Functions

In [23]:
# Built-in functions
fam = [1.73, 1.68, 1.71, 1.89]

print(max(fam))    # Maximum value
print(min(fam))    # Minimum value
print(len(fam))    # Length of list
print(sum(fam))    # Sum of values

1.89
1.68
4
7.01


In [24]:
# Using round()
print(round(1.68, 1))   # Round to 1 decimal
print(round(1.68))      # Round to integer

1.7
2


In [25]:
# Getting help
help(round)
?max  # In Jupyter, you can also use ?

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.

    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.

Object `max  # In Jupyter, you can also use ` not found.


#### 💡 My Experiments:

In [26]:
# Analyzing my study hours
daily_hours = [3.5, 4.0, 3.25, 3.75, 4.0, 5.5, 2.0]

print(f"Study hours this week: {daily_hours}")
print(f"Total hours: {sum(daily_hours)}")
print(f"Average per day: {sum(daily_hours) / len(daily_hours):.2f}")
print(f"Most productive day: {max(daily_hours)} hours")
print(f"Least productive day: {min(daily_hours)} hours")

# Did I meet my 25-hour weekly goal?
weekly_goal = 25
total = sum(daily_hours)
if total >= weekly_goal:
    print(f"\n✅ Goal achieved! Studied {total} hours (goal: {weekly_goal})")
else:
    print(f"\n❌ Fell short. Studied {total} hours (goal: {weekly_goal})")

Study hours this week: [3.5, 4.0, 3.25, 3.75, 4.0, 5.5, 2.0]
Total hours: 26.0
Average per day: 3.71
Most productive day: 5.5 hours
Least productive day: 2.0 hours

✅ Goal achieved! Studied 26.0 hours (goal: 25)


### 3.2 Methods

In [27]:
# String methods
sister = "liz"
print(sister.capitalize())   # Capitalize first letter
print(sister.upper())        # ALL CAPS
print(sister.replace("z", "sa"))  # Replace characters

Liz
LIZ
lisa


In [28]:
# List methods
fam = [1.73, 1.68, 1.71, 1.89]

# index() - find position of element
print(fam.index(1.73))

# count() - count occurrences
print(fam.count(1.73))

0
1


In [29]:
# Methods that modify the list
fam = [1.73, 1.68, 1.71, 1.89]

fam.append(1.79)   # Add element to end
print(fam)

fam.reverse()      # Reverse the list
print(fam)

[1.73, 1.68, 1.71, 1.89, 1.79]
[1.79, 1.89, 1.71, 1.68, 1.73]


#### 💡 My Experiments:

In [30]:
# Understanding the difference: function vs method
skills = ["python", "sql", "excel", "git"]

# Functions: operate on the object as argument
print(f"Using len() function: {len(skills)}")
print(f"Using sorted() function: {sorted(skills)}")
print(f"Original list unchanged: {skills}")

# Methods: called ON the object with dot notation
skills_copy = skills.copy()  # Make a copy to preserve original
skills_copy.sort()           # Modifies in place!
print(f"\nUsing .sort() method: {skills_copy}")
print(f"Original list: {skills}")

Using len() function: 4
Using sorted() function: ['excel', 'git', 'python', 'sql']
Original list unchanged: ['python', 'sql', 'excel', 'git']

Using .sort() method: ['excel', 'git', 'python', 'sql']
Original list: ['python', 'sql', 'excel', 'git']


In [48]:
# Exploring more list methods
todo_list = ["Study Python", "Practice SQL", "Review notes"]

# append() - add one item
todo_list.append("Push to GitHub")
print(f"After append: {todo_list}")

# append() sublist - add a sublist as one item
todo_list.append(["LinkedIn post", "Exercise"])
print(f"After append sublist: {todo_list}")

# extend() - add multiple items
todo_list.extend(["LinkedIn post", "Exercise"])
print(f"After extend: {todo_list}")

# insert() - add at specific position
todo_list.insert(0, "Morning coffee")  # Add at beginning
print(f"After insert: {todo_list}")

# remove() - remove specific item
todo_list.remove("Morning coffee")  # Task complete!
print(f"After remove: {todo_list}")

# pop() - remove and return last item
completed = todo_list.pop()
print(f"Completed: {completed}")
print(f"Remaining: {todo_list}")

After append: ['Study Python', 'Practice SQL', 'Review notes', 'Push to GitHub']
After append sublist: ['Study Python', 'Practice SQL', 'Review notes', 'Push to GitHub', ['LinkedIn post', 'Exercise']]
After extend: ['Study Python', 'Practice SQL', 'Review notes', 'Push to GitHub', ['LinkedIn post', 'Exercise'], 'LinkedIn post', 'Exercise']
After insert: ['Morning coffee', 'Study Python', 'Practice SQL', 'Review notes', 'Push to GitHub', ['LinkedIn post', 'Exercise'], 'LinkedIn post', 'Exercise']
After remove: ['Study Python', 'Practice SQL', 'Review notes', 'Push to GitHub', ['LinkedIn post', 'Exercise'], 'LinkedIn post', 'Exercise']
Completed: Exercise
Remaining: ['Study Python', 'Practice SQL', 'Review notes', 'Push to GitHub', ['LinkedIn post', 'Exercise'], 'LinkedIn post']


### 3.3 Packages

In [32]:
# Import math package
import math

# Use functions from math
print(math.pi)              # Value of pi
print(math.sqrt(16))        # Square root
print(math.ceil(1.7))       # Round up
print(math.floor(1.7))      # Round down

3.141592653589793
4.0
2
1


In [33]:
# Selective import
from math import pi, sqrt

# Now can use without math. prefix
print(pi)
print(sqrt(25))

3.141592653589793
5.0


#### 💡 My Experiments:

In [34]:
# Using math for financial calculations
import math

# Calculate compound interest
principal = 10000
rate = 0.05  # 5%
time = 10    # years

# A = P(1 + r)^t
amount = principal * math.pow((1 + rate), time)
print(f"After {time} years: ${amount:.2f}")

# Using e for continuous compounding
# A = Pe^(rt)
continuous = principal * math.exp(rate * time)
print(f"With continuous compounding: ${continuous:.2f}")

After 10 years: $16288.95
With continuous compounding: $16487.21


---

## Chapter 4: NumPy

### 4.1 NumPy Basics

In [35]:
# Import NumPy
import numpy as np

# Create NumPy array
height = [1.73, 1.68, 1.71, 1.89, 1.79]
np_height = np.array(height)

print(type(np_height))
print(np_height)

<class 'numpy.ndarray'>
[1.73 1.68 1.71 1.89 1.79]


In [36]:
# NumPy array operations (vectorized!)
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
np_weight = np.array(weight)

# Calculate BMI for everyone at once!
bmi = np_weight / np_height ** 2
print(bmi)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


In [37]:
# NumPy subsetting
print(bmi[1])      # Single element
print(bmi > 23)    # Boolean array
print(bmi[bmi > 23])  # Subset with boolean array

20.97505668934241
[False False False  True False]
[24.7473475]


#### 💡 My Experiments:

In [38]:
# Why NumPy is powerful for data analysis
import numpy as np

# Regular list approach (doesn't work!)
monthly_revenue = [50000, 52000, 48000, 55000, 60000]
# monthly_revenue * 1.1  # This would fail!

# NumPy approach (works perfectly!)
np_revenue = np.array(monthly_revenue)
projected_growth = np_revenue * 1.1  # 10% growth

print(f"Current revenue: {np_revenue}")
print(f"Projected (+10%): {projected_growth}")
print(f"Total projected: ${projected_growth.sum():,.0f}")

Current revenue: [50000 52000 48000 55000 60000]
Projected (+10%): [55000. 57200. 52800. 60500. 66000.]
Total projected: $291,500


In [39]:
# Complex filtering with NumPy
import numpy as np

study_hours = np.array([3.5, 4.0, 3.25, 3.75, 4.0, 5.5, 2.0])

# Find days I met my minimum goal (3.5 hours)
goal_met = study_hours >= 3.5
print(f"Days goal met: {goal_met}")
print(f"Number of days: {goal_met.sum()}")  # True = 1, False = 0

# Get actual hours on successful days
successful_days = study_hours[study_hours >= 3.5]
print(f"Hours on successful days: {successful_days}")
print(f"Average on good days: {successful_days.mean():.2f}")

Days goal met: [ True  True False  True  True  True False]
Number of days: 5
Hours on successful days: [3.5  4.   3.75 4.   5.5 ]
Average on good days: 4.15


### 4.2 2D NumPy Arrays

In [40]:
# Create 2D array
import numpy as np

np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])

print(np_2d)
print(np_2d.shape)  # (rows, columns)

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]
(2, 5)


In [41]:
# Subsetting 2D arrays
print(np_2d[0])        # First row
print(np_2d[0][2])     # Element in first row, third column
print(np_2d[0, 2])     # Same thing, better syntax
print(np_2d[:, 1:3])   # All rows, columns 1 and 2

[1.73 1.68 1.71 1.89 1.79]
1.71
1.71
[[ 1.68  1.71]
 [59.2  63.6 ]]


#### 💡 My Experiments:

In [42]:
# Creating a mini dataset
import numpy as np

# Rows: different weeks, Columns: Mon, Tue, Wed, Thu, Fri, Sat, Sun
study_schedule = np.array([
    [3.5, 3.5, 3.5, 3.5, 3.5, 5.5, 2.0],  # Week 1
    [4.0, 3.5, 4.0, 3.5, 4.0, 6.0, 2.0],  # Week 2
    [3.5, 4.0, 3.5, 4.0, 3.5, 5.5, 2.5],  # Week 3
    [4.0, 4.0, 3.5, 3.5, 4.0, 6.0, 2.0]   # Week 4
])

print(f"Shape: {study_schedule.shape}")  # 4 weeks x 7 days
print(f"\nWeek 1 hours: {study_schedule[0]}")
print(f"Total Week 1: {study_schedule[0].sum()}")

# All Saturdays (column 5)
saturdays = study_schedule[:, 5]
print(f"\nSaturday study hours: {saturdays}")
print(f"Average Saturday: {saturdays.mean():.2f}")

# Total hours per week
weekly_totals = study_schedule.sum(axis=1)  # Sum across columns
print(f"\nWeekly totals: {weekly_totals}")
print(f"Monthly total: {weekly_totals.sum()} hours")
print(f"Average per week: {weekly_totals.mean():.2f} hours")

Shape: (4, 7)

Week 1 hours: [3.5 3.5 3.5 3.5 3.5 5.5 2. ]
Total Week 1: 25.0

Saturday study hours: [5.5 6.  5.5 6. ]
Average Saturday: 5.75

Weekly totals: [25.  27.  26.5 27. ]
Monthly total: 105.5 hours
Average per week: 26.38 hours


### 4.3 NumPy Statistics

In [43]:
# NumPy statistical functions
import numpy as np

np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])

print(np.mean(np_height))      # Average
print(np.median(np_height))    # Median
print(np.std(np_height))       # Standard deviation
print(np.corrcoef(np_height, np_weight))  # Correlation

1.7600000000000002
1.73
0.07429670248402682
[[1.         0.97514969]
 [0.97514969 1.        ]]


#### 💡 My Experiments:

In [44]:
# Analyzing performance trends
import numpy as np

# Simulated coding challenge scores over 4 weeks
week1_scores = np.array([60, 65, 70, 72, 75])
week2_scores = np.array([75, 78, 80, 82, 85])
week3_scores = np.array([85, 87, 88, 90, 92])
week4_scores = np.array([90, 92, 94, 95, 97])

# Calculate weekly statistics
weeks = [week1_scores, week2_scores, week3_scores, week4_scores]

for i, week in enumerate(weeks, 1):
    print(f"\nWeek {i}:")
    print(f"  Average: {np.mean(week):.1f}")
    print(f"  Median: {np.median(week):.1f}")
    print(f"  Std Dev: {np.std(week):.2f}")
    print(f"  Best: {np.max(week)}")
    print(f"  Improvement: {week[-1] - week[0]} points")

# Overall trend
all_scores = np.concatenate([week1_scores, week2_scores, week3_scores, week4_scores])
print(f"\nOverall average: {np.mean(all_scores):.1f}")
print(f"Starting score: {all_scores[0]}")
print(f"Final score: {all_scores[-1]}")
print(f"Total improvement: {all_scores[-1] - all_scores[0]} points!")


Week 1:
  Average: 68.4
  Median: 70.0
  Std Dev: 5.31
  Best: 75
  Improvement: 15 points

Week 2:
  Average: 80.0
  Median: 80.0
  Std Dev: 3.41
  Best: 85
  Improvement: 10 points

Week 3:
  Average: 88.4
  Median: 88.0
  Std Dev: 2.42
  Best: 92
  Improvement: 7 points

Week 4:
  Average: 93.6
  Median: 94.0
  Std Dev: 2.42
  Best: 97
  Improvement: 7 points

Overall average: 82.6
Starting score: 60
Final score: 97
Total improvement: 37 points!


---

## 🎯 Key Takeaways

### Chapter 1: Python Basics
1. **Variables store values** - Use descriptive names, follow conventions (lowercase, underscores)
2. **Data types matter** - int, float, str, bool behave differently
3. **Type conversion** - Use `int()`, `float()`, `str()` to convert between types
4. **f-strings are powerful** - Use `f"{variable}"` for clean string formatting

### Chapter 2: Python Lists
1. **Lists are versatile** - Can hold mixed types, are mutable, zero-indexed
2. **Slicing syntax** - `list[start:end:step]` is incredibly powerful
3. **List copying** - Use `list[:]`, `list.copy()`, or `list()` for true copies
4. **Modification methods** - `append()`, `extend()`, `insert()`, `remove()`, `pop()`

### Chapter 3: Functions and Packages
1. **Built-in functions** - `len()`, `max()`, `min()`, `sum()`, `round()`, `sorted()`
2. **Methods vs Functions** - Methods called on objects (`.method()`), functions take arguments
3. **String methods** - `.upper()`, `.lower()`, `.capitalize()`, `.replace()`, `.split()`
4. **Import packages** - `import math` or `from math import sqrt`

### Chapter 4: NumPy
1. **NumPy is fast** - Vectorized operations work on entire arrays at once
2. **Array creation** - `np.array()` converts lists to arrays
3. **Boolean subsetting** - `array[array > 5]` filters in one line
4. **2D arrays** - Access with `array[row, column]`, shape with `.shape`
5. **Statistics** - `mean()`, `median()`, `std()`, `corrcoef()`

---

## 🤔 Questions for Further Learning

1. **When should I use a list vs a NumPy array?**
   - Lists: Mixed types, frequent insertion/deletion, small datasets
   - Arrays: Numerical data, mathematical operations, large datasets

2. **Why does `list.sort()` return None but `sorted(list)` returns a list?**
   - `.sort()` modifies in place (method)
   - `sorted()` returns new list (function)

3. **What's the difference between `append()` and `extend()`?**
   - `append()`: Adds one element (even if it's a list)
   - `extend()`: Adds multiple elements from an iterable

4. **How do I know which packages to import?**
   - Start with built-ins, add packages as needed
   - Common data science stack: NumPy, pandas, matplotlib

5. **What makes NumPy so much faster than lists?**
   - Stores data more efficiently (all same type)
   - Operations implemented in C
   - Vectorization avoids Python loops

---

## 📈 Progress Notes

**Date Completed:** January 18, 2026

**Total Time:** ~4 hours

**Exercises Completed:** All

**Confidence Level:** 
- Python Basics: ⭐⭐⭐⭐⭐
- Lists: ⭐⭐⭐⭐⭐
- Functions: ⭐⭐⭐⭐⭐
- NumPy: ⭐⭐⭐⭐ (need more practice with 2D arrays)

**Next Steps:**
- Practice NumPy with real datasets
- Build mini-project using lists and NumPy
- Move to next course: Intermediate Python

---

## 🔗 Resources

- [DataCamp Course](https://www.datacamp.com/courses/intro-to-python-for-data-science)
- [NumPy Documentation](https://numpy.org/doc/)
- [Python Built-in Functions](https://docs.python.org/3/library/functions.html)
- [My GitHub Repo](https://github.com/manuel-reyes-ml/learning_journey)